---
MetaDataFormat: "yaml"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true
baseurl: "https://jasonheppler.org"
indexes:
  category: "categories"
title: "Jason Heppler"
CanonifyUrls: true
menu:
  main:
      - Name: "About"
        URL: "/about"
        Weight: 2
      - Name: "Research"
        URL: "/publications"
        Weight: 3
      - Name: "Teaching"
        URL: "/teaching"
        Weight: 4
      - Name: "Blog"
        URL: "/blog"
        Weight: 5
      - Name: "Vita"
        URL: "/downloads/pdf/jah-cv.pdf"
        Weight: 6
permalinks:
  blog: /:year/:month/:day/:slug
  archive: /blog/archives/
...
