---
MetaDataFormat: "yaml"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true
baseurl: "http://jasonheppler.org"
indexes:
  category: "categories"
title: "Jason Heppler"
CanonifyUrls: true
menu:
  main:
      - Name: "Research"
        URL: "/publications/"
        Weight: 2
      - Name: "Teaching"
        URL: "/teaching/"
        Weight: 3
      - Name: "Blog"
        URL: "/blog/"
        Weight: 4
      - Name: "Vita"
        URL: "/downloads/pdf/jah-cv.pdf"
        Weight: 5
permalinks:
  blog: /:year/:month/:day/:slug
  archive: /archives/
...
