---
build:
  publish: "public"
  command: "hugo"
context:
  production:
    environment:
      HUGO_VERSION: "0.31.1"
      HUGO_ENV: "production"
      HUGO_ENABLEGITINFO: "true"

MetaDataFormat: "yaml"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true
baseurl: "https://jasonheppler.org"
indexes:
  category: "categories"
title: "Jason Heppler"
CanonifyUrls: true
menu:
  main:
      - Name: "Research"
        URL: "/research/"
        Weight: 2
      - Name: "Teaching"
        URL: "/teaching/"
        Weight: 3
      - Name: "Public History"
        URL: "/public-history/"
        Weight: 4
      - Name: "Talks"
        URL: "/talks/"
        Weight: 5
      - Name: "Blog"
        URL: "/blog/"
        Weight: 6
      - Name: "Vita"
        URL: "https://www.dropbox.com/s/cpbo7md7dooffg1/jah-cv.pdf?dl=0"
        Weight: 7
permalinks:
  blog: /:year/:month/:day/:slug
  archive: /archives/

outputFormats:
  jsonfeed:
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: true

outputs:
  home: ["html", "jsonfeed", "rss"]
---
